accessible_labels:
  footer_navigation: Navegación de pie de página
  login_link_logo: Página de inicio de Login.gov
  partners_link_logo: Página de inicio Login.gov Partners
  primary_navigation: Enlaces primarios
  secondary_navigation: Enlaces secundarios
actions:
  search: Buscar
banner:
  already-have-an-account:
    learn_more: Obtenga más información sobre cómo crear una cuenta
    one_account: Login.gov es su cuenta única para el gobierno
    sign_in: Inicie sesión para administrar su cuenta y actualizar su información
      personal o las opciones de seguridad
    text: ¿Ya tiene una cuenta?
  one-account-for-govt:
    create: Crea una cuenta
    learn: Aprender a crear una cuenta
    tagline: Su única cuenta para el gobierno
  text:
    gov_description: Un sitio web .gov pertenece a una organización oficial del
      Gobierno de Estados Unidos.
    gov_heading: Los sitios web oficiales usan .gov
    how: Así es como sabes
    official: Un sitio web oficial del gobierno de los Estados Unidos
    secure_description: 'Un <strong>candado</strong> o <strong>https://</strong>
      significa que usted se conectó de forma segura a un sitio web .gov.
      Comparta información sensible sólo en sitios web oficiales y seguros.'
    secure_heading: os sitios web seguros .gov usan HTTPS
contact_page:
  call_us:
    operating_hours: 'El horario de servicio es el siguiente: las 24 horas del día,
      los siete días de la semana.'
    title: Llámenos
  operating_hours: 'El horario de servicio es el siguiente: las 24 horas del día,
    los siete días de la semana.'
  required: requerido
  support_request_form:
    agencies:
      'Central Intelligence Agency': Agence centrale de renseignement
      'Consumer Financial Protection Bureau': Oficina para la Protección Financiera del Consumidor
      'Customs and Border Protection Jobs': Trabajos en Aduanas y Protección de Fronteras
      'Customs and Border Protection ROAM': ROAM en Aduanas y Protección de Fronteras
      'Department of Commerce': Departamento de Comercio
      'Department of Defense': Departamento de Defensa
      'Department of Education': Departamento de Educación
      'Department of Energy': Departamento de Energía
      'Department of Homeland Security (DHS)': Departamento de Seguridad Nacional (DHS)
      'Department of Justice (DOJ)': Departamento de Justicia (DOJ)
      'Department of Labor': Departamento del Trabajo
      'Department of State': Departamento de Estado
      'Department of the Interior': Departamento del Interior
      'Department of the Treasury': Departamento del Tesoro
      'Department of Transportation': Departamento de Transporte
      'Department of Veterans Affairs': Departamento de Asuntos de los Veteranos
      'DOI ePermits': Permisos electrónicos del Departamento del Interior (DOI)
      'DOL Foreign Labor Application Gateway (FLAG)': Portal de solicitud de mano de
        obra extranjera (FLAG) del Departamento del Trabajo (DOL)
      'DOT Delphi eInvoicing': Facturación electrónica en Delphi del Departamento de Transporte (DOT)
      'DOT FMCSA (Motor Carrier Safety)': FMCSA del Departamento de Transporte (Seguridad de Autotransportes)
      'DOT National Registry of Certified Medical Examiners': Registro Nacional de
        Examinadores Médicos Certificados del Departamento de Transporte
      'Environmental Protection Agency': Agencia de Protección Ambiental
      'FDIC Resolution Request Management Portal': Portal de administración de
        resoluciones de solicitudes de la Corporación Federal de Seguro de
        Depósitos (FDIC)
      'FEMA Disaster Assistance': Asistencia de FEMA en caso de catástrofe
      'General Services Administration': Administración de Servicios Generales
      'Get.gov': Get.gov
      'GSA Sam.gov': GSA SAM.gov
      'Health and Human Services': Departamento de Salud y Servicios Humanos
      'HHS Grants.gov': Grants.gov del HHS
      'HHS National Institutes of Health (NIH)': Institutos Nacionales de la Salud
      'Housing and Urban Development': Departamento de Vivienda y Desarrollo Urbano de EE. UU.
      'Internal Revenue Service (IRS)': Servicio de Impuestos Internos (IRS)
      'Library of Congress': Biblioteca del Congreso
      'MyTravelGov': Departamento de Estado MyTravelGov
      'myTreasury': myTreasury
      'National Aeronautics and Space Administration': Administración Nacional de Aeronáutica y el Espacio
      'National Archives and Records Administration (NARA)': Archivos Nacionales y Administracion de Documentos (NARA)
      'National Credit Union Administration (NCUA)': Administración Nacional de Cooperativas de Crédito (NCUA)
      'National Endowment for the Humanities (NEH)': Fondo Nacional para las Humanidades (NEH, siglas en inglés)
      'National Labor Relations Board': Junta Nacional de Relaciones Laborales
      'National Transportation Safety Board (NTSB)': Junta Nacional de Seguridad en el Transporte (NTSB)
      'Office of Personnel Management': Oficina de Administración de Personal (OPM)
      'OPM Employee Express': OPM Empleado Express
      'OPM Services Online': 'Servicios en línea de OPM'
      'Pay.gov': Pay.gov
      'PBGC-MyPBA': 'PBGC - MyPBA'
      'Peace Corps': Cuerpo de Paz
      'Railroad Retirement Board': Junta de Jubilación del Ferrocarril
      'SBA DLAP': SBA DLAP
      'Securities and Exchange Commission': Comisión de Bolsa y Valores
      'Social Security Administration (SSA)': Administración del Seguro Social (SSA, por su siglas en inglés)
      'State of Arkansas': Estado de Arkansas
      'State of California': Estado de California
      'State of Colorado': Estado de Colorado
      'Trusted Traveler Programs (Global Entry/Nexus/Sentri)': Programas de Viajero de Confianza (Global Entry/Nexus/Sentri)
      'U.S. Agency for International Development': Agencia de los Estados Unidos para el Desarrollo Internacional
      'U.S. Department of Agriculture': Departamento de Agricultura de los Estados Unidos
      'U.S. International Trade Commission': Comisión Internacional de Comercio de los Estados Unidos
      'United States Forest Service': Servicio Forestal de los Estados Unidos
      'USAJOBS': USAJOBS
    errors:
      captcha_required: Debes superar el desafío de prevención de spam.
      pii_found: Por su privacidad, no envíe información confidencial en este
        formulario. Nuestros agentes de atención al cliente pueden atenderle
        igualmente sin esta información.
    form_helpers:
      select_agency: '- Seleccione Agencia a la que intenta acceder-'
      select_issue: '- Seleccione un problema específico -'
      select_topic: '- Seleccione un tema -'
    labels:
      agency_application: Aplicación de agencia
      agency_application_all: Todas las aplicaciones
      agency_application_common: Aplicaciones comunes
      agency_application_other: Otras aplicaciones
      description: Proporcione más detalles. Si necesita ayuda, por favor describa los
        pasos que dio y los problemas que encontró.
      email: Correo electrónico
      first_name: Nombre
      last_name: Apellido
      pii_warning: 'No incluya números de teléfono, números de socio, nombres
        completos, cumpleaños, direcciones, números de la seguridad social u
        otros datos identificativos.'
      subtopic: Subtema del problema
      topic: Tema del problema
    other: Otro
    required_text: Los campos obligatorios están marcados con un asterisco
    reset: Limpiar formulario
    submit: Enviar
    subtopics:
      account_locked: Mi cuenta está bloqueada desde hace 24 horas
      add_family_member: ¿Cómo añado un familiar a mi cuenta de Login.gov?
      agency_app: Problema con la aplicación de la agencia
      authentication_app: Tengo una aplicación de autenticación pero no funciona
      authentication_app_setup: ¿Cómo configuro una aplicación de autenticación?
      backup_codes: ¿Cómo utilizo mis códigos de copia de seguridad para iniciar sesión?
      blank_screen: Veo un error/pantalla en blanco al crear mi cuenta
      cant_proof_in_person: No pude verificar mi identidad en persona en la oficina de correos
      change_email: ¿Cómo cambio mi correo electrónico?
      change_password: ¿Cómo actualizo mi contraseña de Login.gov?
      change_phone_number: ¿Cómo cambio mi número de teléfono?
      concerned_login_email: Estoy preocupado por el correo electrónico de Login.gov que he recibido
      delete_account: ¿Cómo elimino mi cuenta de Login.gov?
      device_notification: He recibido una alerta sobre un nuevo inicio de sesión en
        mi cuenta de Login.gov
      email_delivery_issue: No recibo el correo electrónico de confirmación de Login.gov
      feedback: Tengo comentarios sobre Login.gov
      forgot_password: Olvidé mi contraseña de Login.gov y no puedo restablecerla
      how_to_create_with_verification: ¿Cómo puedo crear una cuenta en Login.gov con verificación de identidad?
      how_to_link: ¿Cómo puedo vincular la cuenta de mi agencia asociada con Login.gov?
      how_to_verify: ¿Cómo/por qué verifico mi identidad?
      interest_in_partnership: Estoy interesado en utilizar Login.gov para mi agencia gubernamental
      international_number: Tengo un número internacional y no recibo mi código de seguridad
      invalid_email: Login.gov no acepta mi dirección de correo electrónico. Dice que
        no es válido
      invalid_otp: Login.gov dice que mi código de seguridad no es válido
      issue_with_partner_agency: Tengo un problema con esta agencia asociada
      issues_with_face_touch_unlock: Tengo problemas con el uso del desbloqueo facial o táctil
      letter_in_mail: No he recibido mi carta por correo o ha caducado
      locked_out: Estoy bloqueado en mi cuenta
      lost_2fa_method: Método autenticación de dos factores perdido
      lost_access: He perdido el acceso a mi teléfono o dirección de correo electrónico
      multiple_otps: Recibo códigos de seguridad de Login.gov que no he solicitado
      new_account: Mi correo electrónico/nombre de usuario y contraseña no funcionan
      new_backup_codes: ¿Cómo consigo nuevos códigos de copia de seguridad?
      new_device_notification: He recibido un correo electrónico de notificación de nuevo dispositivo
      new_personal_key: ¿Cómo puedo obtener una nueva clave personal?
      no_otp_received: No se ha recibido ningún pedido de pago
      no_phone: No puedo crear mi cuenta de Login.gov porque no tengo un teléfono
      none: '--Ninguno--'
      other: Otro
      password_issue: Problema con la contraseña
      personal_key: Mi clave personal no funciona
      personal_key_notification: He recibido una alerta sobre un nuevo inicio de
        sesión en mi cuenta de Login.gov
      personal_key_setup: Configuración de la clave personal
      phone_number_failure: He recibido un fallo después de introducir mi número de teléfono
      piv_cac: Tengo problemas para usar mi PIV/CAC para iniciar sesión
      privacy_and_security: Privacidad y seguridad
      recover_account: ¿Cómo puedo entrar en mi cuenta si no tengo mi teléfono o mi
        clave personal?
      remember_browser: He configurado el navegador para recordar, pero sigo
        recibiendo códigos de seguridad
      remember_device_issue: ¿Cómo puedo dejar de recibir los códigos de seguridad?
      security_code: No recibo el código de seguridad
      security_key: Tengo problemas para usar mi clave de seguridad para iniciar sesión
      security_question: ¿Cómo protege Login.gov mi privacidad y seguridad?
      seeing_errors: Veo una pantalla de error/en blanco cuando accedo a Login.gov
      service_quality: Calidad del servicio
      site_navigation: No sé dónde ir para crear una cuenta
      state_issued_id_error: Tengo un error después de subir mi documento de identidad
        emitido por el estado
      unwanted_otp: Recibo muchos códigos de seguridad al iniciar sesión
      verify_identity_error: He recibido un fallo al intentar verificar mi identidad
      wrong_account_update: Actualización de la cuenta errónea
    title: Enviar un tíquet de ayuda
    topics:
      changing_settings: Cambiar su información de Login.gov
      creating_account: Crear una cuenta de Login.gov
      feedback: Comentarios o otro
      not_login_gov: No es Login.gov
      other: Otro
      piv_cac: Problema con CAC (tarjeta de acceso común) o PIV (verificación de
        identidad personal)
      security_codes: Códigos de seguridad de Login.gov
      signing_in: Iniciar sesión en su cuenta de Login.gov
      verifying_identity: Verificar su identidad
feedback_form:
  'no': 'No'
  question: ¿Te resultó útil este artículo?
  'yes': 'Si'
global:
  language: Idioma
  locales:
    en: English
    es: Español
    fr: Français
    zh: Chinese
help_page:
  categories:
    - description: Cree su cuenta. Conozca las opciones de autenticación y más
        características de la cuenta.
      image: /assets/img/help/get-started.svg
      title: Empiece con Login.gov
      url: /es/help/get-started/overview/
    - description: ¿Olvidó su contraseña? ¿Se bloqueó su cuenta? Le ayudaremos a
        solucionar los problemas de acceso.
      image: /assets/img/help/trouble-signing-in.svg
      title: ¿Tiene problemas para iniciar sesión?
      url: /es/help/trouble-signing-in/overview/
    - description: Cambia la configuración de la cuenta, incluida la contraseña, el
        teléfono, el correo electrónico y más.
      image: /assets/img/help/manage-your-account.svg
      title: Administrar su cuenta
      url: /es/help/manage-your-account/overview/
    - description: Obtenga ayuda con Trusted Traveler Programs (TTP), SAM.gov.
      image: /assets/img/help/help-specific-agencies.svg
      title: Asistencia de agencias específicas
      url: /es/help/specific-agencies/overview/
    - description: Aprenda sobre las opciones para verificar su identidad.
      image: /assets/img/help/verify-your-id.svg
      title: Verifique su identidad
      url: /es/help/verify-your-identity/overview/
  p_1: Explore los temas comunes
  title: ¿Cómo podemos ayudar?
help_subpages:
  get-started: Empiece con Login.gov
  manage-your-account: Administrar su cuenta
  specific-agencies: Ayuda con agencias específicas
  trouble-signing-in: ¿Tiene problemas para iniciar sesión?
  verify-your-identity: Verificación de identidad
identifier:
  accessible_labels:
    description: Descripción de la agencia
    gsa_link_logo: Página de inicio de GSA
    identifier: Identificador de la agencia
    links: Enlaces importantes
    login_gov_logo: Logotipo de Login.gov
    usa_gov: Información y servicios del Gobierno de EE. UU.
  disclaimer: Un sitio web oficial de [General Services
    Administration](https://www.gsa.gov)
  links:
    about_agency: Acerca de GSA
    accessibility: Soporte de accesibilidad
    foia: Solicitud a través de FOIA
    ig: Oficina del Inspector General
    no_fear_act: Datos de la ley No FEAR
    performance: Informes de desempeño
    privacy: Política de privacidad
  usa_gov:
    link: Visite USAGov en Español
    text: ¿Necesita información y servicios del Gobierno?
nav:
  about_us:
    sections:
      - name: Nuestra misión
        url: '#nuestra-misión'
      - name: Nuestra visión
        url: '#nuestra-visión'
      - name: Acerca de Login.gov
        url: '#acerca-de-logingov'
    title: Acerca de nosotros
  accessibility:
    sections:
      - name: Nuestro compromiso
        url: '#nuestro-compromiso'
      - name: Estándares
        url: '#estándares'
      - name: Evaluación
        url: '#evaluación'
      - name: Limitaciones conocidas
        url: '#limitaciones-conocidas'
    title: Accesibilidad
  anchor_to_top: Volver arriba
  become_a_partner: Convertirse en un compañero
  business_inquiries:
    title: Business inquiries

  contact_login_gov: Póngase en contacto con Login.gov
  contact_us:
    sections:
      - name: Busque respuesta a las preguntas más frecuentes
        url: '#busque-respuesta-a-las-preguntas-más-frecuentes'
      - name: Póngase en contacto
        url: '#póngase-en-contacto'
      - name: Asóciese con Login.gov
        url: '#asóciese-con-logingov'
      - name: Informe de un problema
        url: '#informe-de-un-problema'
    title: Contacta con nosotros
  create_an_account: Crea una cuenta
  developer_guide: Guía para desarrolladores
  developers: Desarrolladores
  faq: FAQ
  get_started: Get started # partners site does not require translations
  groups:
    about_login_gov: About Login.gov # partners site does not require translations
    agencies: Para agencias
    learn: Aprender
    partners: For partners # partners site does not require translations
    support: Apoyo
  help: Ayuda
  help_center: Centro de ayuda
  home: Inicio
  implementation: Implementación
  join_us:
    sections:
      - name: Puestos vacantes
        url: '#puestos-vacantes'
      - name: Cómo presentar solicitud
        url: '#cómo-presentar-solicitud'
    title: Únete a nuestro equipo
  menu: Menú
  overview: Resumen
  playbook: Manual
  policies:
    sections:
      - name: Nuestro compromiso con su privacidad y seguridad
        url: /es/policy/
      - name: ¿Cómo funciona?
        url: /es/policy/how-does-it-work/
      - name: Nuestra declaración de la ley de privacidad
        url: /es/policy/our-privacy-act-statement/
      - name: Términos y condiciones de mensajería
        url: /es/policy/messaging-terms-and-conditions/
      - name: Reglas de uso
        url: /es/policy/rules-of-use/
    title: Privacidad y seguridad
    url: /es/policy/
  principles: Principios
  privacy_&_security: Privacidad y seguridad
  security: Seguridad
  security_experience: Security experience # partners site does not require translations
  sign_in: 'Inicie sesión con'
  skip_nav: Salte al contenido principal
  system_status: Estado del sistema Login.gov
  what_is_login_gov: ¿Qué es Login.gov?
  who_uses_login_gov: ¿Quién usa Login.gov?
