accessible_labels:
  secondary_navigation: Navegación secundaria
actions:
  search: Buscar
banner:
  already-have-an-account:
    learn_more: Obtenga más información sobre cómo crear una cuenta
    one_account: Login.gov es su cuenta única para el gobierno
    sign_in: Inicie sesión para administrar su cuenta y actualizar su información personal o las opciones de seguridad
    text: ¿Ya tiene una cuenta?
  one-account-for-govt:
    create: Crea una cuenta
    learn: Aprender a crear una cuenta
    tagline: Su única cuenta para el gobierno
  text:
    official: Un sitio web oficial del gobierno de los Estados Unidos
    how: Así es como sabes
    gov_heading: Los sitios web oficiales usan .gov
    gov_description: Un sitio web .gov pertenece a una organización oficial del Gobierno de Estados Unidos.
    secure_heading: os sitios web seguros .gov usan HTTPS
    secure_description: 'Un <strong>candado</strong> o <strong>https://</strong> significa que usted se conectó de forma segura a un sitio web .gov. Comparta información sensible sólo en sitios web oficiales y seguros.'
contact_page:
  support_request_form:
    other: Otro
    agencies:
      "Customs and Border Protection Jobs": Trabajos en Aduanas y Protección de Fronteras
      "Customs and Border Protection ROAM": ROAM en Aduanas y Protección de Fronteras
      "DOD Moves.mil (Homes or Office)": DOD Move.mil (Hogares u oficinas)
      "DOT FMCSA (Motor Carrier Safety)": FMCSA del Departamento de Transporte (Seguridad de Autotransportes)
      "DOT National Registry of Certified Medical Examiners": Registro Nacional de Examinadores Médicos Certificados del Departamento de Transporte
      "GSA Sam.gov": GSA SAM.gov
      "PBGC-MyPBA": "PBGC - MyPBA"
      "Railroad Retirement Board": Junta de Jubilación del Ferrocarril
      "SBA DLAP": SBA DLAP
      "Social Security Administration (SSA)": Administración del Seguro Social (SSA, por su siglas en inglés)
      "Trusted Traveler Programs (Global Entry/Nexus/Sentri)": Programas de Viajero de Confianza (Global Entry/Nexus/Sentri)
      "USAJOBS": USAJOBS
      "Veterans Affairs": Asuntos de Veteranos
    errors:
      captcha_required: Debes superar el desafío de prevención de spam.
    form_helpers:
      select_topic: '- Seleccione un tema -'
      select_issue: '- Seleccione un problema específico -'
      select_agency: '- Seleccione una solicitud de agencia -'
    labels:
      agency_application: Aplicación de agencia
      agency_application_all: Todas las aplicaciones
      agency_application_common: Aplicaciones comunes
      agency_application_other: Otras aplicaciones
      description: Proporciona más detalles acerca de tu pregunta
      email: Correo electrónico
      first_name: Nombre
      last_name: Apellido
      pii_warning: '**No** incluya información sensible o de identificación en esta sección, como su nombre completo, fecha de nacimiento o número de seguro social.'
      subtopic: Subtema del problema
      topic: Tema del problema
      optional: opcional
    reset: Limpiar formulario
    submit: Enviar
    subtopics:
      account_locked: Mi cuenta está bloqueada desde hace 24 horas
      add_family_member: ¿Cómo añado un familiar a mi cuenta de Login.gov?
      agency_app: Problema con la aplicación de la agencia
      authentication_app: Tengo una aplicación de autenticación pero no funciona
      authentication_app_setup: ¿Cómo configuro una aplicación de autenticación?
      backup_codes: ¿Cómo utilizo mis códigos de copia de seguridad para iniciar sesión?
      blank_screen: Veo un error/pantalla en blanco al crear mi cuenta
      change_email: ¿Cómo cambio mi correo electrónico?
      change_password: ¿Cómo actualizo mi contraseña de Login.gov?
      change_phone_number: ¿Cómo cambio mi número de teléfono?
      delete_account: ¿Cómo elimino mi cuenta de Login.gov?
      device_notification: He recibido una alerta sobre un nuevo inicio de sesión en mi cuenta de Login.gov       email_delivery_issue: No recibo el correo electrónico de confirmación de Login.gov       forgot_password: Olvidé mi contraseña de Login.gov y no puedo restablecerla
      international_number: Tengo un número internacional y no recibo mi código de seguridad
      invalid_email: Login.gov no acepta mi dirección de correo electrónico. Dice que no es válido
      invalid_otp: Login.gov dice que mi código de seguridad no es válido
      letter_in_mail: No he recibido mi carta por correo o ha caducado
      locked_out: Estoy bloqueado en mi cuenta
      lost_2fa_method: Método autenticación de dos factores perdido
      multiple_otps: Recibo códigos de seguridad de Login.gov que no he solicitado
      new_account: Mi correo electrónico/nombre de usuario y contraseña no funcionan
      new_backup_codes: ¿Cómo consigo nuevos códigos de copia de seguridad?
      new_personal_key: ¿Cómo puedo obtener una nueva clave personal?
      no_otp_received: No se ha recibido ningún pedido de pago
      no_phone: No puedo crear mi cuenta de Login.gov porque no tengo un teléfono
      none: '--Ninguno--'
      other: Otro
      password_issue: Problema con la contraseña
      personal_key: Mi clave personal no funciona
      personal_key_setup: Configuración de la clave personal
      personal_key_notification: He recibido una alerta sobre un nuevo inicio de sesión en mi cuenta de Login.gov
      phone_number_failure: He recibido un fallo después de introducir mi número de teléfono
      piv_cac: Tengo problemas para usar mi PIV/CAC para iniciar sesión
      privacy_and_security: Privacidad y seguridad
      recover_account: ¿Cómo puedo entrar en mi cuenta si no tengo mi teléfono o mi clave personal?
      remember_device_issue: ¿Cómo puedo dejar de recibir los códigos de seguridad?
      security_code: No recibo el código de seguridad
      security_key: Tengo problemas para usar mi clave de seguridad para iniciar sesión
      service_quality: Calidad del servicio
      site_navigation: No sé dónde ir para crear una cuenta
      state_issued_id_error: Tengo un error después de subir mi documento de identidad emitido por el estado
      unwanted_otp: Recibo muchos códigos de seguridad al iniciar sesión
      verify_identity_error: He recibido un fallo al intentar verificar mi identidad
      wrong_account_update: Actualización de la cuenta errónea
    topics:
      account_linking: Vincular su cuenta de Login.gov a su perfil
      changing_settings: Cambiar su información de Login.gov
      creating_account: Crear una cuenta de Login.gov
      feedback: Comentarios para Login.gov
      not_login_gov: No es Login.gov
      other: Otro
      piv_cac: Problema con CAC (tarjeta de acceso común) o PIV (verificación de identidad
        personal)
      security_codes: Códigos de seguridad de Login.gov
      signing_in: Iniciar sesión en su cuenta de Login.gov
      verifying_identity: Verificar su identidad
feedback_form:
  'yes': "Si"
  'no': "No"
  question: ¿Te resultó útil este artículo?
footer:
  gsa: Administración General de Servicios de EE. UU.
global:
  language: Idioma
  locales:
    en: English
    es: Español
    fr: Français
help_page:
  p_1: Explore los temas comunes
  title: ¿Cómo podemos ayudar?
  categories:
    - title: Empiece con Login.gov
      description: Cree su cuenta. Conozca las opciones de autenticación y más características de la cuenta.
      url: /es/help/get-started/overview/
      image: /assets/img/help/get-started.svg
    - title: ¿Tiene problemas para iniciar sesión?
      description: ¿Olvidó su contraseña? ¿Se bloqueó su cuenta? Le ayudaremos a solucionar los problemas de acceso.
      url: /es/help/trouble-signing-in/overview/
      image: /assets/img/help/trouble-signing-in.svg
    - title: Administrar su cuenta
      description: Cambia la configuración de la cuenta, incluida la contraseña, el teléfono, el correo electrónico y más.
      url: /es/help/manage-your-account/overview/
      image: /assets/img/help/manage-your-account.svg
    - title: Asistencia de agencias específicas
      description: Obtenga ayuda con Trusted Traveler Programs (TTP), SAM.gov.
      url: /es/help/specific-agencies/overview/
      image: /assets/img/help/help-specific-agencies.svg
    - title: Verifique su identidad
      description: Aprenda sobre las opciones para verificar su identidad.
      url: /es/help/verify-your-identity/overview/
      image: /assets/img/help/verify-your-id.svg
help_subpages:
  get-started: Empiece con Login.gov   trouble-signing-in: ¿Tiene problemas para iniciar sesión?
  manage-your-account: Administrar su cuenta
  specific-agencies: Ayuda con agencias específicas
  verify-your-identity: Verificación de identidad
nav:
  accessibility:
    title: Accesibilidad
    sections:
      - name: Nuestro compromiso
        url: '#nuestro-compromiso'
      - name: Estándares
        url: '#estándares'
      - name: Evaluación
        url: '#evaluación'
      - name: Limitaciones conocidas
        url: '#políticas-de-accesibilidad'
  about_us: Sobre nosotros
  anchor_to_top: Volver arriba
  become_a_partner: Convertirse en un compañero
  contact_us:
    title: Contacta con nosotros
    sections:
      - name: ¿Tiene alguna pregunta sobre la cuenta de su agencia?
        url: '#tiene-alguna-pregunta-sobre-la-cuenta-de-su-agencia'
      - name: Asociarse con Login.gov         url: '#asociarse-con-logingov'
      - name: Reportar un problema
        url: '#reportar-un-problema'
  contact_login_gov: Póngase en contacto con Login.gov
  create_an_account: Crea una cuenta
  developer_guide: Guía para desarrolladores
  developers: Desarrolladores
  groups:
    agencies: Para agencias
    learn: Aprender
    support: Apoyo
  help: Ayuda
  help_center: Centro de ayuda
  home: Inicio
  implementation: Implementación
  menu: Menú
  overview: Resumen
  playbook: Manual
  policies:
    title: Privacidad y seguridad
    sections:
      - name: Nuestro compromiso con su privacidad y seguridad
        url: /es/policy/
      - name: ¿Cómo funciona?
        url: /es/policy/how-does-it-work/
      - name: Nuestra declaración de la ley de privacidad
        url: /es/policy/our-privacy-act-statement/
      - name: Nuestras prácticas de seguridad
        url: /es/policy/our-security-practices/
      - name: Términos y condiciones de mensajería
        url: /es/policy/messaging-terms-and-conditions/
      - name: Reglas de uso
        url: /es/policy/rules-of-use/
  principles: Principios
  privacy_&_security: Privacidad y seguridad
  security: Seguridad
  sign_in: 'Inicie sesión con'
  skip_nav: Salte al contenido principal
  system_status: Estado del sistema Login.gov   what_is_login_gov: ¿Qué es Login.gov?
  who_uses_login_gov: ¿Quién usa Login.gov?
policies:
  title: Privacidad y seguridad
  sections:
    - name: Nuestro compromiso con su privacidad y seguridad
      url: '/policy/'
      sublinks:
        - text: Cómo trabajamos con nuestras agencias asociadas
          url: '#how-we-work-with-our-partner-agencies'
    - name: ¿Cómo funciona?
      url: '/policy/how-does-it-work/'
    - name: Nuestra declaración de la ley de privacidad
      url: '/policy/our-privacy-act-statement/'
      sublinks:
        - text: La Autoridad - ¿Quién autoriza la recopilación de estos datos?
          url: '#authority'
        - text: El propósito - ¿Por qué necesitamos su información?
          url: '#purpose'
        - text: Usos de rutina - ¿Con quién se comparte habitualmente la información?
          url: '#routine-uses'
        - text: Consentimiento - ¿Cómo puede controlar qué información se comparte?
          url: '#consent'
        - text: Registros - ¿Dónde puede encontrar más información?
          url: '#records'
        - text: Análisis de sitios web
          url: '#analytics'
        - text: Evaluación del impacto en la privacidad
          url: '#impact'
    - name: Nuestras prácticas de seguridad
      url: '/policy/our-security-practices/'
      sublinks:
        - text: Política de divulgación de vulnerabilidades
          url: '#vdp'
        - text: Para más información
          url: '#more-info'
    - name: Términos y condiciones de mensajería
      url: '/policy/messaging-terms-and-conditions/'
      sublinks:
        - text: Términos y condiciones de SMS
          url: '#terms'
    - name: Reglas de uso
      url: '/policy/rules-of-use/'
create-an-account:
  hero:
    heading: Crea una cuenta
    text: Únase a los millones de personas que confían en Login.gov para tener acceso seguro a agencias gubernamentales.
  intro: Cuando esté listo para crear su cuenta segura de Login.gov, deberá proporcionar algunos datos&#58;
  step_1: |-
    ## 1. Dirección de correo electrónico
      * Recomendamos una dirección de correo electrónico personal a la que siempre podrá acceder en lugar de una dirección de correo electrónico del trabajo.
      * Si ya tiene una cuenta con Login.gov con esa dirección de correo electrónico, le enviaremos un correo electrónico para informarle cómo puede restablecer su contraseña y acceder a la cuenta.
  step_2: |-
    ## 2. Contraseña segura
      * Las contraseñas deben tener al menos 12 caracteres y no deben incluir palabras o frases de uso común.
  step_3: |-
    ## 3. Uno o más [métodos de autenticación](__LOCALE_BASE_URL__/help/authentication-methods/which-authentication-method-should-i-use/) como&#58;
      * __Mas segura__
        * Clave de seguridad
        * Aplicación de autenticación
        * Identificación militar o de empleado del gobierno federal (PIV / CAC)
      * __Menos segura__
        * SMS / mensajes de texto
        * Códigos de respaldo
  info: Dependiendo de las necesidades de seguridad de la agencia, es posible que deba probar su identidad mediante un número de seguro social, una dirección y / o una identificación emitida por Los Estados Unidos.
identifier:
  accessible_labels:
    description: Descripción de la agencia
    identifier: Identificador de la agencia
    links: Enlaces importantes
    logo: Logo de la GSA
    usa_gov: Información y servicios del Gobierno de EE. UU.
  disclaimer: Un sitio web oficial de [General Services Administration](https://gsa.gov)
  links:
    about_agency: Acerca de GSA
    accessibility: Soporte de accesibilidad
    foia: Solicitud a través de FOIA
    ig: Oficina del Inspector General
    no_fear_act: Datos de la ley No FEAR
    performance: Informes de desempeño
    privacy: Política de privacidad
  usa_gov:
    text: ¿Necesita información y servicios del Gobierno?
    link: Visite USAGov en Español
