# Netlify CMS Settings
## Comment out when doing local development
backend:
  name: github
  repo: GSA-TTS/identity-site
  branch: main
  base_url: https://pages.cloud.gov
  auth_endpoint: external/auth/github
  preview_context: pages/build
  use_graphql: true
#
# Uncomment when doing local development on Netlify CMS
# Run `npx netlify-cms-proxy-server` to start working locally
# In another terminal, start the app with `make build && make run`
# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
#
#
# backend:
#   name: git-gateway
#   branch: main
#   proxy_url: http://localhost:8081/api/v1
# local_backend: true

media_folder: 'assets/img/'
public_folder: '/img/uploads'
publish_mode: editorial_workflow

i18n:
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [_en, _es, _fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: _en

editor:
  preview: true

display_url: https://login.gov

collections:
  - label: Help articles
    label_singular: 'Help article'
    name: help
    folder: content/_help/
    i18n: true
    create: true
    path: '{{category}}/{{slug}}'
    summary: '{{title}} ({{category}}/{{filename}}.{{extension}})'
    filter: { field: 'layout', value: 'help' }
    sortable_fields: ['category', 'commit_date', 'title', 'commit_author']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'help' }
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1', i18n: true }
      - {
          label: 'Category',
          name: category,
          widget: 'select',
          options:
            [
              { label: 'Get started with Login.gov', value: 'get-started' },
              { label: 'Manage your account', value: 'manage-your-account' },
              { label: 'Trouble signing in?', value: 'trouble-signing-in' },
              { label: 'Verify your identity', value: 'verify-your-identity' },
              { label: 'Help with specific agencies', value: 'specific-agencies' },
            ],
          default: 'get-started',
          i18n: duplicate,
        }
      - { label: 'Permalink', name: 'permalink', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Meta Title', name: 'meta_title', widget: 'string', required: false, i18n: true }
      - { label: 'Order', name: 'order', widget: 'number', default: 10, min: 0, i18n: duplicate }
      - {
          label: 'Redirect from',
          name: 'redirect_from',
          widget: 'list',
          hint: 'Comma-separated list of urls.',
          required: false,
          i18n: true,
        }
      - {
          label: 'Redirect to',
          name: 'redirect_to',
          widget: 'string',
          required: false,
          i18n: duplicate,
        }
  - label: Landing pages
    label_singular: 'Landing page'
    name: page
    folder: content/_landing
    i18n: true
    create: true
    path: '{{slug}}'
    summary: '{{title}} ({{filename}}.{{extension}})'
    filter: { field: 'layout', value: 'landing' }
    sortable_fields: ['commit_date', 'title', 'commit_author']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'landing' }
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Class', name: 'class', widget: 'string', required: false, i18n: duplicate }
      - label: 'Two Column'
        name: 'component'
        widget: 'object'
        i18n: true
        collapsed: true
        required: false
        fields:
          - { label: 'Column 1', name: 'col1', widget: 'markdown', required: false, i18n: true }
          - {
              label: 'Banner Text',
              name: bannertext,
              widget: markdown,
              required: false,
              i18n: true,
            }
          - {
              label: 'Text Banner Column 1',
              name: bannercol1,
              widget: markdown,
              required: false,
              i18n: true,
            }
          - {
              label: 'Text Banner Column 2',
              name: bannercol2,
              widget: markdown,
              required: false,
              i18n: true,
            }
          - { label: 'Column 2', name: 'col2', widget: 'markdown', required: false, i18n: true }
      - label: 'Three Column'
        name: 'three_col'
        widget: 'object'
        i18n: true
        collapsed: true
        required: false
        fields:
          - { label: 'Heading', name: 'heading', widget: 'string', required: false, i18n: true }
          - {
              label: 'Subheading 1',
              name: 'subheading1',
              widget: 'string',
              required: false,
              i18n: true,
            }
          - { label: 'Column 1', name: 'col1', widget: 'markdown', required: false, i18n: true }
          - {
              label: 'Subheading 2',
              name: 'subheading2',
              widget: 'string',
              required: false,
              i18n: true,
            }
          - { label: 'Column 2', name: 'col2', widget: 'markdown', required: false, i18n: true }
          - {
              label: 'Subheading 3',
              name: 'subheading3',
              widget: 'string',
              required: false,
              i18n: true,
            }
          - { label: 'Column 3', name: 'col3', widget: 'markdown', required: false, i18n: true }
      - label: 'Steps Page'
        name: 'steps'
        widget: 'object'
        i18n: true
        collapsed: true
        required: false
        fields:
          - { label: 'Intro', name: intro, widget: 'markdown', required: false, i18n: true }
          - { label: 'Step 1', name: step1, widget: markdown, required: false, i18n: true }
          - { label: 'Step 2', name: 'step2', widget: 'markdown', required: false, i18n: true }
          - { label: 'Step 3', name: 'step3', widget: 'markdown', required: false, i18n: true }
          - { label: 'Info text', name: 'info', widget: 'markdown', required: false, i18n: true }
      - { label: 'Permalink', name: 'permalink', widget: 'string', i18n: true }
      - {
          label: 'Twitter card',
          name: 'twitter_card',
          widget: 'select',
          default: 'large',
          i18n: duplicate,
          options: ['small', 'large'],
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          default: '/assets/img/login-gov-600x314.png',
          i18n: duplicate,
        }
      - { label: 'Redirect from', name: 'redirect_from', widget: list, required: false, i18n: true }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false, i18n: true }
  - label: Policy pages
    label_singular: 'Policy page'
    name: policy
    folder: content/_policy
    i18n: true
    create: true
    path: '{{slug}}'
    summary: '{{title}} ({{filename}}.{{extension}})'
    filter: { field: 'layout', value: 'sidenav' }
    sortable_fields: ['commit_date', 'title', 'commit_author']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'sidenav' }
      - {
          label: 'Page type',
          name: 'sidenav',
          widget: 'select',
          default: 'policies',
          options: ['policies', 'accessibility', 'contact_us', about_us, 'none'],
          i18n: duplicate,
        }
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Permalink', name: 'permalink', widget: 'string', i18n: true }
      - { label: 'Redirect from', name: 'redirect_from', widget: list, required: false, i18n: true }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false, i18n: true }
      - { label: 'Order', name: 'index', widget: 'number', i18n: duplicate, required: false }
  - label: Contact us
    name: contact
    folder: content/_policy
    i18n: true
    path: '{{slug}}'
    summary: '{{title}} ({{filename}}.{{extension}})'
    filter: { field: 'layout', value: 'contact_us' }
    sortable_fields: ['commit_date', 'title', 'commit_author']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'sidenav' }
      - {
          label: 'Page type',
          name: 'sidenav',
          widget: 'hidden',
          default: 'contact_us',
          i18n: duplicate,
        }
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Intro', name: 'intro_content', widget: 'markdown', i18n: true }
      - { label: 'Footer', name: 'footer_content', widget: 'markdown', i18n: true }
      - {
          label: 'Scripts',
          name: 'scripts',
          widget: 'file',
          allow_multiple: true,
          default: '/assets/js/contact.js',
          i18n: duplicate,
        }
      - { label: 'Permalink', name: 'permalink', widget: 'string', i18n: true }
      - { label: 'Redirect from', name: 'redirect_from', widget: list, required: false, i18n: true }
      - { label: 'Redirect to', name: 'redirect_to', widget: 'string', required: false, i18n: true }
  - label: Program updates
    label_singular: 'Program update'
    name: program_updates
    folder: content/_program_updates
    i18n: false
    create: true
    path: '{{slug}}'
    summary: '{{title}} ({{filename}}.{{extension}})'
    filter: { field: 'layout', value: 'sidenav' }
    sortable_fields: ['commit_date', 'date', 'title', 'commit_author']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'sidenav' }
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1', required: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish date', name: 'date', widget: 'datetime', required: true }      
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
