accessible_labels:
  secondary_navigation: Secondary navigation
actions:
  search: Search
banner:
  already-have-an-account:
    learn_more: Learn more about creating an account
    one_account: Login.gov is your one account for government
    sign_in: Sign in to manage your account
    text: Already have an account?
  one-account-for-govt:
    create: Create an account
    learn: Learn how to create an account
    tagline: Your one account for government
  text:
    official: An official website of the United States government
    how: Here’s how you know
    gov_heading: Official websites use .gov
    gov_description: A <strong>.gov</strong> website belongs to an official government organization in the United States.
    secure_heading: Secure .gov websites use HTTPS
    secure_description: 'A <strong>lock</strong> or <strong>https://</strong> means you’ve safely connected to the .gov website. Share sensitive information only on official, secure websites.'
contact_page:
  support_request_form:
    agencies:
      cbp_jobs: Customs and Border Protection Jobs
      cbp_roam: Customs and Border Protection ROAM
      dot_fmcsa: DOT FMCSA (Motor Carrier Safety)
      dot_nrcme: DOT National Registry of Certified Medical Examiners
      ds_logon: DS Logon
      move_mil: DOD Move.mil (Homes or Office)
      other: Other
      railroad_retirement_board: Railroad Retirement Board
      sam: GSA SAM.gov
      sba_dlap: SBA DLAP
      ssa: Social Security Administration (SSA)
      trusted_traveler_program: Trusted Traveler Programs (Global Entry/Nexus/Sentri)
      usajobs: USAJOBS
      veterans_affairs: Veterans Affairs
    errors:
      captcha_required: You must complete the spam prevention challenge.
    form_helpers:
      select_topic: '- Select a topic -'
      select_issue: '- Select a specific issue -'
      select_agency: '- Select an agency application -'
    labels:
      agency_application: Agency application
      agency_application_all: All Applications
      agency_application_common: Common Applications
      agency_application_other: Other Applications
      description: Provide more detail about your question
      email: Email
      first_name: First name
      last_name: Last name
      pii_warning: Please do **not** include sensitive or identifying information in this section such as your full name, birth date or social security number.
      subtopic: Issue
      topic: Topic
      optional: optional
    reset: Clear form
    submit: Submit
    subtopics:
      account_locked: My account is locked for 24 hours
      add_family_member: How do I add a family member to my login.gov account?
      agency_app: Agency app issue
      authentication_app: How do I change my authentication method?
      authentication_app_setup: How do I set up an authentication app?
      backup_codes: How do I use my backup codes to sign in?
      blank_screen: I'm seeing an error/blank screen when creating my account
      change_email: How do I change my email?
      change_password: How do I update my login.gov password?
      change_phone_number: How do I change my phone number?
      delete_account: How do I delete my login.gov account?
      device_notification: I have received an alert about a new sign in on my login.gov account
      email_delivery_issue: I am not receiving the login.gov confirmation email
      forgot_password: I forgot my login.gov password and can't reset it
      international_number: I have an international number and am not receiving my security code
      invalid_email: login.gov is not accepting my email address. It says it is invalid
      invalid_otp: Login.gov says my security code is invalid
      letter_in_mail: I didn't get my letter by mail or it expired
      locked_out: I am locked out of my account
      lost_2fa_method: Lost two-factor authentication method
      multiple_otps: I am receiving many security codes when signing in
      new_account: My email/username and password are not working
      new_backup_codes: How do I get new backup codes?
      new_personal_key: How do I get a new personal key?
      no_otp_received: No OTP received
      no_phone: I can't create my login.gov account because I don't have a phone
      none: '--None--'
      other: Other
      password_issue: Password issue
      personal_key: My personal key is not working
      personal_key_notification: I have received an alert about my personal key being used to sign in
      personal_key_setup: Personal key setup
      phone_number_failure: I got a failure after entering my phone number
      piv_cac: I am having trouble using my PIV/CAC to sign in
      privacy_and_security: Privacy and security
      recover_account: How do I sign into my account if I dont have my phone or personal key?
      remember_device_issue: How do I stop receiving security codes?
      security_code: I am not receiving the security code
      security_key: I am having trouble using my security key to sign in
      service_quality: Service quality
      site_navigation: I don't know where to go to create an account
      state_issued_id_error: I got an error after uploading my state-issued ID
      unwanted_otp: I am receiving security codes from login.gov that I didn't request
      verify_identity_error: I got a failure trying to verify my identity
      wrong_account_update: Wrong account update
    topics:
      account_linking: Linking your login.gov account to your profile
      changing_settings: Changing your login.gov information
      creating_account: Create a login.gov account
      feedback: Feedback for login.gov
      not_login_gov: Not login.gov
      other: Other
      piv_cac: PIV/CAC issue
      security_codes: Login.gov security codes
      signing_in: Signing in to your login.gov account
      verifying_identity: Verifying your identity
feedback_form:
  'yes': "Yes"
  'no': "No"
  question: "Was this article helpful?"
global:
  language: Language
  locales:
    en: English
    es: Español
    fr: Français
help_page:
  p_1: Browse common topics
  title: How can we help?
  categories:
    - title: Get started with login.gov
      description: Create your account. Learn about authentication options and more account features.
      url: /help/get-started/overview/
      image: /assets/img/help/get-started.svg
    - title: Trouble signing in?
      description: Forgot your password? Locked out of your account? We'll help you resolve access issues.
      url: /help/trouble-signing-in/overview/
      image: /assets/img/help/trouble-signing-in.svg
    - title: Manage your account
      description: Change your account settings including your password, phone number, email, and more.
      url: /help/manage-your-account/overview/
      image: /assets/img/help/manage-your-account.svg
    - title: Help with specific agencies
      description: Get help with Trusted Traveler Programs (TTP) and SAM.gov.
      url: /help/specific-agencies/overview/
      image: /assets/img/help/help-specific-agencies.svg
    - title: Verify your identity
      description: Learn about options for verifying your identity.
      url: /help/verify-your-identity/overview/
      image: /assets/img/help/verify-your-id.svg
help_subpages:
  get-started: Get started with login.gov
  trouble-signing-in: Trouble signing in?
  manage-your-account: Manage your account
  specific-agencies: Help with specific agencies
  verify-your-identity: Verify your identity
meta:
  accessibility:
    description: Read our accessibility statement
    title: Accessibility
  contact:
    title: Contact
  contact_us:
    description: Have a question or a problem with login.gov?
    title: Contact us
  developers:
    title: Partners
  help:
    description: Get answers to common questions about login.gov.
    title: Help
  home:
    description: Use one account for secure, private access to Federal benefits and services.
    title: Home
  implementation:
    description: Determine whether your agency or organization needs a consumer identity
      management system.
    title: Implementation
  not_found:
    title: '404'
  our-agency-partners:
    description: Join the dozens of U.S. government agencies using login.gov. Learn more about how login.gov can benefit your agency.
    title: Our agency partners
  partners:
    description: We help government agencies manage, secure and optimize the login experience for their websites, services and applications.
    title: Partner with login.gov
  playbook:
    description: Helping developers and technologists in government agencies build
      usable, secure, and privacy-protecting consumer identity management systems.
    title: Identity Playbook
  principles:
    description: Explore the principles that have helped us make the best system possible.
    title: Principles
  privacy_and_security:
    description: Learn more about our security and privacy practices.
    title: Privacy & security
  privacy_policy:
    title: Privacy policy
  what-is-login:
    title: What is login.gov?
    description: A summary of what login.gov is and the service it provides.
  who-uses-login:
    title: Who uses login.gov?
    description: A list of customers currently benefitting from login.gov's services
  why-login-gov:
    title: Why login.gov
    description: U.S. government agencies can take advantage of login.gov’s authentication and identity proofing platform. Find out more about login.gov’s offerings and opportunities.
  create-an-account:
    title: Create an account
    description: Join the millions of people who trust login.gov for safe, secure access to government agencies.
nav:
  accessibility:
    title: Accessibility statement
    sections:
      - name: Our Commitment
        url: '#our-commitment'
      - name: Standards
        url: '#standards'
      - name: Evaluation
        url: '#evaluation'
      - name: Known limitations
        url: '#known-limitations'
  anchor_to_top: Back to top
  about_us: About us
  become_a_partner: Become a partner
  contact_us:
    title: Contact us
    sections:
      - name: Do you have a question about your agency account?
        url: '#do-you-have-a-question-about-your-agency-account'
      - name: Partner with login.gov
        url: '#partner-with-logingov'
      - name: Report an issue
        url: '#report-an-issue'
  contact_login_gov: Contact Login.gov
  create_an_account: Create an account
  developer_guide: Developer guide
  developers: developers
  groups:
    agencies: For agencies
    learn: Learn
    support: Support
  help: Help
  help_center: Help center
  home: Home
  implementation: Implementation
  menu: Menu
  overview: Overview
  our-agency-partners: Our agency partners
  partners: Partners
  playbook: Playbook
  policies:
    title: Privacy & security
    sections:
      - name: Our commitment to your privacy and security
        url: /policy/
      - name: How does it work?
        url: /policy/how-does-it-work/
      - name: Our privacy act statement
        url: /policy/our-privacy-act-statement/
      - name: Our security practices
        url: /policy/our-security-practices/
      - name: Messaging terms and conditions
        url: /policy/messaging-terms-and-conditions/
      - name: Rules of use
        url: /policy/rules-of-use/
  principles: Principles
  privacy_&_security: Privacy & security
  security: Security
  sign_in: 'Sign in with'
  skip_nav: Skip to main content
  system_status: login.gov system status
  what_is_login_gov: What is login.gov?
  who_uses_login_gov: Who uses login.gov?
policies:
  title: Privacy & security
  sections:
    - name: Our commitment to your privacy and security
      url: '/policy/'
      sublinks:
        - text: How we work with our partner agencies
          url: '#how-we-work-with-our-partner-agencies'
    - name: How does it work?
      url: '/policy/how-does-it-work/'
    - name: Our privacy act statement
      url: '/policy/our-privacy-act-statement/'
      sublinks:
        - text: The Authority - Who authorizes the collection of this data?
          url: '#authority'
        - text: The Purpose - Why do we need your information?
          url: '#purpose'
        - text: Routine Uses - With whom is the information routinely shared?
          url: '#routine-uses'
        - text: Consent - How can you control what information is shared?
          url: '#consent'
        - text: Records - Where can you find more information?
          url: '#records'
        - text: Website Analytics
          url: '#analytics'
        - text: Privacy Impact Assessment
          url: '#impact'
    - name: Our security practices
      url: '/policy/our-security-practices/'
      sublinks:
        - text: Vulnerability disclosure policy
          url: '#vdp'
        - text: For more information
          url: '#more-info'
    - name: Messaging terms and conditions
      url: '/policy/messaging-terms-and-conditions/'
      sublinks:
        - text: SMS terms and conditions
          url: '#terms'
    - name: Rules of use
      url: '/policy/rules-of-use/'
create-an-account:
  hero:
    heading: Create an account
    text: Join the millions of people who trust login.gov for safe, secure access to government agencies.
  intro: When you’re ready to create your secure login.gov account, you’ll need to provide a few pieces of information&#58;
  step_1: |-
    ## 1. Email address
      * We recommend a personal email address that you’ll always be able to access rather than a work email address.
      * If you already have an account with login.gov with that email address, we’ll send you an email to let you know how you can reset your password and access the account.
  step_2: |-
    ## 2. Secure password
      * Passwords must be at least 12 characters and should not include commonly used words or phrases.
  step_3: |-
    ## 3. One or more [authentication methods](__LOCALE_BASE_URL__/help/authentication-methods/which-authentication-method-should-i-use/) such as:
      * __More secure__
        * Security Key
        * Authentication application
        * Federal government employee or military identification (PIV/CAC)
      * __Less secure__
        * SMS/Text messages
        * Backup codes
  info: Depending on the security needs of the agency, you may need to prove your identity using a social security number, address, and/or U.S. based state-issued identification.
identifier:
  accessible_labels:
    description: Agency description
    identifier: Agency identifier
    links: Important links
    logo: GSA logo
    usa_gov: U.S. government information and services
  disclaimer: An official website of the [General Services Administration](https://gsa.gov)
  links:
    about_agency: About GSA
    accessibility: Accessibility support
    foia: FOIA requests
    ig: Office of the Inspector General
    no_fear_act: No FEAR Act data
    performance: Performance reports
    privacy: Privacy policy
  usa_gov:
    text: Looking for U.S. government information and services?
    link: Visit USA.gov
